name: E2E

on:
  pull_request:
    paths:
      - ".github/workflows/*.yml"
      - "package.json"
      - "packages/kubernetes-client/package.json"
      - "packages/kubernetes-client/src/**"
      - "packages/kubernetes-client-fetch/package.json"
      - "packages/kubernetes-client-fetch/src/**"
      - "packages/kubernetes-client-angular/projects/**"
      - "packages/kubernetes-client-angular/package.json"
      - "packages/kubernetes-client-example-fetch/package.json"
      - "packages/kubernetes-client-example-fetch/playwright.config.ts"
      - "packages/kubernetes-client-example-fetch/src/**"
      - "packages/kubernetes-client-example-fetch/tests/**"

jobs:

  playwright:
    timeout-minutes: 60
    strategy:
      matrix:
        example:
          - kubernetes-client-example-fetch
          - kubernetes-client-angular
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'npm'
      - name: Install dependencies
        run: make -f .github/workflows/e2e.mk -e example=${{ matrix.example }} -j 2 preinstall
      - name: Setup test tools
        run: make -f .github/workflows/e2e.mk -e example=${{ matrix.example }} -j 2 install
      - name: Run tests
        run: make -f .github/workflows/e2e.mk -e example=${{ matrix.example }} e2e
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: packages/${{ matrix.example }}/playwright-report/
          retention-days: 30
