name: PullRequest

on:
  pull_request:
    paths-ignore:
      - "**/README.md"
      - ".github/**"

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'npm'
      - run: npm install
      - run: npm run lint
      - name: Ensure clean git state
        run: git diff --exit-code
