name: PullRequest

on:
  pull_request: { }

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'npm'
      - run: npm install
      - run: npm run lint
      - name: Ensure clean git state
        run: git diff --exit-code

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'npm'
      - run: npm install
      - run: npm run test

  dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'npm'
      - run: npm install
      - run: npm run build

  e2e:
    timeout-minutes: 60
    strategy:
      matrix:
        example:
          - kubernetes-client-example-fetch
          - kubernetes-client-angular
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'npm'
      - name: Install dependencies
        run: make -f .github/workflows/e2e.mk -e example=${{ matrix.example }} -j 2 preinstall
      - name: Setup test tools
        run: make -f .github/workflows/e2e.mk -e example=${{ matrix.example }} -j 2 install
      - name: Run tests
        run: make -f .github/workflows/e2e.mk -e example=${{ matrix.example }} e2e
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: packages/${{ matrix.example }}/playwright-report/
          retention-days: 30
